class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'folders': 'Klasörler',
      'peers': 'Peer\'lar',
      'transfers': 'Transferler',
      'profile': 'Profil',
      'nickname': 'Kullanıcı Adı',
      'save': 'Kaydet',
      'saved': 'Kaydedildi',
      'theme_mode': 'Görünüm Modu',
      'light_mode': 'Aydınlık Mod',
      'dark_mode': 'Karanlık Mod',
      'language_option': 'Dil Seçeneği',
      'login': 'Giriş yap',
      'signup': 'Kayıt Ol',
      'p2p_connections': 'P2P Bağlantılar',
      'this_device': 'Bu Cihaz',
      'discovered': 'Keşfedilen',
      'connected': 'Bağlı',
      'refresh': 'Yenile',
      'no_peers_found': 'Peer Bulunamadı',
      'no_peers_message': 'Aynı ağdaki diğer Aether cihazları otomatik olarak keşfedilir.',
      'search_again': 'Yeniden Ara',
      'no_connected_peers': 'Bağlı Peer Yok',
      'no_connected_message': 'Keşfedilen peer\'lara bağlanmak için "Keşfedilen" sekmesine gidin.',
      'connect': 'Bağlan',
      'disconnect': 'Bağlantıyı Kes',
      'trust': 'Güven',
      'untrust': 'Güveni Kaldır',
      'online': 'Çevrimiçi',
      'offline': 'Çevrimdışı',
      'connecting': 'Bağlanıyor',
      'unknown': 'Bilinmiyor',
      'show_details': 'Detayları Göster',
      'remove_peer': 'Peer\'ı Kaldır',
      'close': 'Kapat',
      'cancel': 'İptal',
      'remove': 'Kaldır',
      'remove_confirm_title': 'Peer\'ı Kaldır',
      'remove_confirm_message': 'peer\'ını kaldırmak istediğinize emin misiniz?',
      'disconnect_confirm_title': 'Bağlantıyı Kes',
      'disconnect_confirm_message': 'cihazıyla bağlantıyı kesmek istediğinize emin misiniz?',
      'name_saved': 'İsim kaydedildi',
      'no_folders': 'Henüz klasör eklenmedi',
      'add_folder': 'Klasör Ekle',
      'active': 'Aktif',
      'inactive': 'Pasif',
      'delete': 'Sil',
      'error': 'Hata',
      'enter_nickname': 'Kullanıcı adı girin',
      'appearance': 'Görünüm',
      'language': 'Dil',
      'subscription': 'Abonelik',
      'file_transfers': 'Dosya Transferleri',
      'completed': 'Tamamlandı',
      'failed': 'Başarısız',
      'no_active_transfers': 'Aktif Transfer Yok',
      'transfers_will_appear_here': 'Dosya transferleri burada görünecek.',
      'folder_detail': 'Klasör Detayı',
      'sender': 'Gönderici',
      'last_scan': 'Son Tarama',
      'status': 'Durum',
      'no_connected_peers_folder': 'Bağlı peer yok',
      'just_now': 'Az önce',
      'minutes_ago': 'dakika önce',
      'hours_ago': 'saat önce',
      'days_ago': 'gün önce',
      'sync_bidirectional': 'İki Yönlü',
      'sync_receive_only': 'Sadece Al',
      'sync_send_only': 'Sadece Gönder',
      'sync_unspecified': 'Henüz Belirlenmemiş',
      'unknown_status': 'Bilinmiyor',
      'notifications': 'Bildirimler',
      'clear': 'Temizle',
      'delete_folder_title': 'Klasörü Sil',
      'delete_folder_message': 'Bu klasörü senkronizasyondan kaldırmak istediğinizden emin misiniz?',
      'delete_physically': 'Bilgisayarımdan tamamen kaldır',
      'delete_physically_subtitle': 'İşaretlenirse klasör ve tüm dosyalar bilgisayardan silinir',
      'delete_warning': '⚠️ UYARI: Klasör ve tüm içeriği bilgisayardan silinecek!',
      'delete_info': 'ℹ️ Klasör sadece uygulamadan kaldırılacak, dosyalar korunacak.',
      'delete_permanently': 'Tamamen Sil',
      'remove_from_app': 'Uygulamadan Kaldır',
      'folder_deleted_physically': 'Klasör bilgisayardan tamamen silindi',
      'folder_removed_app': 'Klasör uygulamadan kaldırıldı (dosyalar korundu)',
      'selected_folder': 'Seçilen Klasör:',
      'sync_mode_selection_info': 'Senkronizasyon modu, dosyayı gönderirken seçilebilir.',
      'folder_added_success': 'Klasör başarıyla eklendi!',
      'no_notifications': 'Bildirim yok',
      'delete_file_title': 'Dosyayı Sil',
      'delete_file_message': 'Bu dosyayı silmek istediğinizden emin misiniz?',
      'file_deleted_physically': 'Dosya bilgisayardan tamamen silindi',
      'file_removed_app': 'Dosya uygulamadan kaldırıldı',
      'upload_profile_photo': 'Profil fotoğrafı yükle',
      'change_profile_photo': 'Profil fotoğrafını değiştir',
      'remove_profile_photo': 'Profil fotoğrafını sil',
    },
    'en': {
      'folders': 'Folders',
      'peers': 'Peers',
      'transfers': 'Transfers',
      'profile': 'Profile',
      'nickname': 'Nickname',
      'save': 'Save',
      'saved': 'Saved',
      'theme_mode': 'Appearance',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'language_option': 'Language',
      'login': 'Log in',
      'signup': 'Sign up',
      'p2p_connections': 'P2P Connections',
      'this_device': 'This Device',
      'discovered': 'Discovered',
      'connected': 'Connected',
      'refresh': 'Refresh',
      'no_peers_found': 'No Peers Found',
      'no_peers_message': 'Other Aether devices on the same network are discovered automatically.',
      'search_again': 'Search Again',
      'no_connected_peers': 'No Connected Peers',
      'no_connected_message': 'Go to the "Discovered" tab to connect to peers.',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'trust': 'Trust',
      'untrust': 'Untrust',
      'online': 'Online',
      'offline': 'Offline',
      'connecting': 'Connecting',
      'unknown': 'Unknown',
      'show_details': 'Show Details',
      'remove_peer': 'Remove Peer',
      'close': 'Close',
      'cancel': 'Cancel',
      'remove': 'Remove',
      'remove_confirm_title': 'Remove Peer',
      'remove_confirm_message': 'Are you sure you want to remove peer',
      'disconnect_confirm_title': 'Disconnect',
      'disconnect_confirm_message': 'Are you sure you want to disconnect from',
      'name_saved': 'Name saved',
      'no_folders': 'No folders added yet',
      'add_folder': 'Add Folder',
      'active': 'Active',
      'inactive': 'Inactive',
      'delete': 'Delete',
      'error': 'Error',
      'enter_nickname': 'Enter nickname',
      'appearance': 'Appearance',
      'language': 'Language',
      'subscription': 'Subscription',
      'file_transfers': 'File Transfers',
      'completed': 'Completed',
      'failed': 'Failed',
      'no_active_transfers': 'No Active Transfers',
      'transfers_will_appear_here': 'File transfers will appear here.',
      'folder_detail': 'Folder Detail',
      'sender': 'Sender',
      'last_scan': 'Last Scan',
      'status': 'Status',
      'no_connected_peers_folder': 'No connected peers',
      'just_now': 'Just now',
      'minutes_ago': 'min ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'sync_bidirectional': 'Bidirectional',
      'sync_receive_only': 'Receive Only',
      'sync_send_only': 'Send Only',
      'sync_unspecified': 'Unspecified',
      'unknown_status': 'Unknown',
      'notifications': 'Notifications',
      'clear': 'Clear',
      'delete_folder_title': 'Delete Folder',
      'delete_folder_message': 'Are you sure you want to remove this folder from synchronization?',
      'delete_physically': 'Remove from my computer completely',
      'delete_physically_subtitle': 'If checked, the folder and all files will be deleted from the computer',
      'delete_warning': '⚠️ WARNING: Folder and all contents will be deleted from the computer!',
      'delete_info': 'ℹ️ Folder will only be removed from the app, files will be preserved.',
      'delete_permanently': 'Delete Permanently',
      'remove_from_app': 'Remove from App',
      'folder_deleted_physically': 'Folder deleted from computer completely',
      'folder_removed_app': 'Folder removed from app (files preserved)',
      'selected_folder': 'Selected Folder:',
      'sync_mode_selection_info': 'Sync mode can be selected when sending files.',
      'add': 'Add',
      'folder_added_success': 'Folder added successfully!',
      'no_notifications': 'No notifications',
      'delete_file_title': 'Delete File',
      'delete_file_message': 'Are you sure you want to delete this file?',
      'file_deleted_physically': 'File deleted from computer completely',
      'file_removed_app': 'File removed from app',
      'upload_profile_photo': 'Upload Profile Photo',
      'change_profile_photo': 'Change Profile Photo',
      'remove_profile_photo': 'Remove Profile Photo',
    },
    'de': {
      'folders': 'Ordner',
      'peers': 'Peers',
      'transfers': 'Übertragungen',
      'profile': 'Profil',
      'nickname': 'Benutzername',
      'save': 'Speichern',
      'saved': 'Gespeichert',
      'theme_mode': 'Erscheinungsbild',
      'light_mode': 'Heller Modus',
      'dark_mode': 'Dunkler Modus',
      'language_option': 'Sprache',
      'login': 'Anmelden',
      'signup': 'Registrieren',
      'p2p_connections': 'P2P-Verbindungen',
      'this_device': 'Dieses Gerät',
      'discovered': 'Entdeckt',
      'connected': 'Verbunden',
      'refresh': 'Aktualisieren',
      'no_peers_found': 'Keine Peers gefunden',
      'no_peers_message': 'Andere Aether-Geräte im selben Netzwerk werden automatisch entdeckt.',
      'search_again': 'Erneut suchen',
      'no_connected_peers': 'Keine verbundenen Peers',
      'no_connected_message': 'Gehen Sie zum Tab "Entdeckt", um sich mit Peers zu verbinden.',
      'connect': 'Verbinden',
      'disconnect': 'Trennen',
      'trust': 'Vertrauen',
      'untrust': 'Vertrauen entziehen',
      'online': 'Online',
      'offline': 'Offline',
      'connecting': 'Verbindet',
      'unknown': 'Unbekannt',
      'show_details': 'Details anzeigen',
      'remove_peer': 'Peer entfernen',
      'close': 'Schließen',
      'cancel': 'Abbrechen',
      'remove': 'Entfernen',
      'remove_confirm_title': 'Peer entfernen',
      'remove_confirm_message': 'Möchten Sie den Peer wirklich entfernen',
      'disconnect_confirm_title': 'Trennen',
      'disconnect_confirm_message': 'Möchten Sie die Verbindung wirklich trennen zu',
      'name_saved': 'Name gespeichert',
      'no_folders': 'Noch keine Ordner hinzugefügt',
      'add_folder': 'Ordner hinzufügen',
      'active': 'Aktiv',
      'inactive': 'Inaktiv',
      'delete': 'Löschen',
      'error': 'Fehler',
      'enter_nickname': 'Benutzername eingeben',
      'appearance': 'Erscheinungsbild',
      'language': 'Sprache',
      'subscription': 'Abonnement',
      'file_transfers': 'Dateiübertragungen',
      'completed': 'Abgeschlossen',
      'failed': 'Fehlgeschlagen',
      'no_active_transfers': 'Keine aktiven Übertragungen',
      'transfers_will_appear_here': 'Dateiübertragungen werden hier angezeigt.',
      'folder_detail': 'Ordnerdetails',
      'sender': 'Absender',
      'last_scan': 'Letzter Scan',
      'status': 'Status',
      'no_connected_peers_folder': 'Keine verbundenen Peers',
      'just_now': 'Gerade eben',
      'minutes_ago': 'Minuten vor',
      'hours_ago': 'Stunden vor',
      'days_ago': 'Tagen vor',
      'sync_bidirectional': 'Bidirektional',
      'sync_receive_only': 'Nur Empfangen',
      'sync_send_only': 'Nur Senden',
      'sync_unspecified': 'Nicht spezifiziert',
      'unknown_status': 'Unbekannt',
      'notifications': 'Benachrichtigungen',
      'clear': 'Löschen',
      'delete_folder_title': 'Ordner löschen',
      'delete_folder_message': 'Möchten Sie diesen Ordner wirklich aus der Synchronisation entfernen?',
      'delete_physically': 'Vollständig vom Computer entfernen',
      'delete_physically_subtitle': 'Wenn aktiviert, werden der Ordner und alle Dateien vom Computer gelöscht',
      'delete_warning': '⚠️ WARNUNG: Ordner und gesamter Inhalt werden vom Computer gelöscht!',
      'delete_info': 'ℹ️ Ordner wird nur aus der App entfernt, Dateien bleiben erhalten.',
      'delete_permanently': 'Dauerhaft löschen',
      'remove_from_app': 'Aus App entfernen',
      'folder_deleted_physically': 'Ordner vollständig vom Computer gelöscht',
      'folder_removed_app': 'Ordner aus App entfernt (Dateien erhalten)',
      'selected_folder': 'Ausgewählter Ordner:',
      'sync_mode_selection_info': 'Synchronisationsmodus kann beim Senden von Dateien ausgewählt werden.',
      'add': 'Hinzufügen',
      'folder_added_success': 'Ordner erfolgreich hinzugefügt!',
      'no_notifications': 'Keine Benachrichtigungen',
      'delete_file_title': 'Datei löschen',
      'delete_file_message': 'Möchten Sie diese Datei wirklich löschen?',
      'file_deleted_physically': 'Datei vollständig vom Computer gelöscht',
      'file_removed_app': 'Datei aus App entfernt',
      'upload_profile_photo': 'Profilbild hochladen',
      'change_profile_photo': 'Profilbild ändern',
      'remove_profile_photo': 'Profilbild entfernen',
    },
  };

  static String get(String key, String langCode) {
    return _localizedValues[langCode]?[key] ?? key;
  }
}
