name: aether_desktop
description: Aether P2P File Sync - Desktop UI
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # gRPC
  grpc: ^3.2.4
  protobuf: ^3.1.0
  
  # Utils
  path: ^1.9.0
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  
  # Storage
  # shared_preferences: ^2.2.2  # Şimdilik devre dışı
  
  # Icons
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700





