// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMode int32

const (
	SyncMode_SYNC_MODE_UNSPECIFIED   SyncMode = 0
	SyncMode_SYNC_MODE_BIDIRECTIONAL SyncMode = 1
	SyncMode_SYNC_MODE_SEND_ONLY     SyncMode = 2
	SyncMode_SYNC_MODE_RECEIVE_ONLY  SyncMode = 3
)

// Enum value maps for SyncMode.
var (
	SyncMode_name = map[int32]string{
		0: "SYNC_MODE_UNSPECIFIED",
		1: "SYNC_MODE_BIDIRECTIONAL",
		2: "SYNC_MODE_SEND_ONLY",
		3: "SYNC_MODE_RECEIVE_ONLY",
	}
	SyncMode_value = map[string]int32{
		"SYNC_MODE_UNSPECIFIED":   0,
		"SYNC_MODE_BIDIRECTIONAL": 1,
		"SYNC_MODE_SEND_ONLY":     2,
		"SYNC_MODE_RECEIVE_ONLY":  3,
	}
)

func (x SyncMode) Enum() *SyncMode {
	p := new(SyncMode)
	*p = x
	return p
}

func (x SyncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[0].Descriptor()
}

func (SyncMode) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[0]
}

func (x SyncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMode.Descriptor instead.
func (SyncMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{0}
}

type PeerStatus int32

const (
	PeerStatus_PEER_STATUS_UNKNOWN PeerStatus = 0
	PeerStatus_PEER_STATUS_ONLINE  PeerStatus = 1
	PeerStatus_PEER_STATUS_OFFLINE PeerStatus = 2
)

// Enum value maps for PeerStatus.
var (
	PeerStatus_name = map[int32]string{
		0: "PEER_STATUS_UNKNOWN",
		1: "PEER_STATUS_ONLINE",
		2: "PEER_STATUS_OFFLINE",
	}
	PeerStatus_value = map[string]int32{
		"PEER_STATUS_UNKNOWN": 0,
		"PEER_STATUS_ONLINE":  1,
		"PEER_STATUS_OFFLINE": 2,
	}
)

func (x PeerStatus) Enum() *PeerStatus {
	p := new(PeerStatus)
	*p = x
	return p
}

func (x PeerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[1].Descriptor()
}

func (PeerStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[1]
}

func (x PeerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerStatus.Descriptor instead.
func (PeerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{1}
}

type UserRole int32

const (
	UserRole_USER_ROLE_STANDARD UserRole = 0
	UserRole_USER_ROLE_ADMIN    UserRole = 1
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_STANDARD",
		1: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_STANDARD": 0,
		"USER_ROLE_ADMIN":    1,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[2].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[2]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_api_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_api_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

var File_api_proto_common_proto protoreflect.FileDescriptor

const file_api_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/common.proto\x12\n" +
	"aether.api\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"P\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"y\n" +
	"\x12PaginationResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage*w\n" +
	"\bSyncMode\x12\x19\n" +
	"\x15SYNC_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SYNC_MODE_BIDIRECTIONAL\x10\x01\x12\x17\n" +
	"\x13SYNC_MODE_SEND_ONLY\x10\x02\x12\x1a\n" +
	"\x16SYNC_MODE_RECEIVE_ONLY\x10\x03*V\n" +
	"\n" +
	"PeerStatus\x12\x17\n" +
	"\x13PEER_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12PEER_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13PEER_STATUS_OFFLINE\x10\x02*7\n" +
	"\bUserRole\x12\x16\n" +
	"\x12USER_ROLE_STANDARD\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01B(Z&github.com/aether/sync/api/proto;protob\x06proto3"

var (
	file_api_proto_common_proto_rawDescOnce sync.Once
	file_api_proto_common_proto_rawDescData []byte
)

func file_api_proto_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)))
	})
	return file_api_proto_common_proto_rawDescData
}

var file_api_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_common_proto_goTypes = []any{
	(SyncMode)(0),              // 0: aether.api.SyncMode
	(PeerStatus)(0),            // 1: aether.api.PeerStatus
	(UserRole)(0),              // 2: aether.api.UserRole
	(*Empty)(nil),              // 3: aether.api.Empty
	(*Status)(nil),             // 4: aether.api.Status
	(*PaginationRequest)(nil),  // 5: aether.api.PaginationRequest
	(*PaginationResponse)(nil), // 6: aether.api.PaginationResponse
}
var file_api_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_common_proto_init() }
func file_api_proto_common_proto_init() {
	if File_api_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_proto_depIdxs,
		EnumInfos:         file_api_proto_common_proto_enumTypes,
		MessageInfos:      file_api_proto_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_proto = out.File
	file_api_proto_common_proto_goTypes = nil
	file_api_proto_common_proto_depIdxs = nil
}
