// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,3,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	GlobalHash    string                 `protobuf:"bytes,6,opt,name=global_hash,json=globalHash,proto3" json:"global_hash,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,7,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *File) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *File) GetGlobalHash() string {
	if x != nil {
		return x.GlobalHash
	}
	return ""
}

func (x *File) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *File) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *File) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Chunk struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId             string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Offset             int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length             int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	DeviceAvailability []string               `protobuf:"bytes,5,rep,name=device_availability,json=deviceAvailability,proto3" json:"device_availability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Chunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Chunk) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Chunk) GetDeviceAvailability() []string {
	if x != nil {
		return x.DeviceAvailability
	}
	return nil
}

type FileVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	VersionNumber   int32                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	BackupPath      string                 `protobuf:"bytes,4,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	OriginalPath    string                 `protobuf:"bytes,5,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	Size            int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Hash            string                 `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedByPeerId string                 `protobuf:"bytes,9,opt,name=created_by_peer_id,json=createdByPeerId,proto3" json:"created_by_peer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileVersion) Reset() {
	*x = FileVersion{}
	mi := &file_api_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersion) ProtoMessage() {}

func (x *FileVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersion.ProtoReflect.Descriptor instead.
func (*FileVersion) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileVersion) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileVersion) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *FileVersion) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *FileVersion) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *FileVersion) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileVersion) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileVersion) GetCreatedByPeerId() string {
	if x != nil {
		return x.CreatedByPeerId
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_api_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_api_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ListFilesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_api_proto_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_api_proto_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileInfoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type FileInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	File           *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Chunks         []*Chunk               `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	AvailablePeers []string               `protobuf:"bytes,4,rep,name=available_peers,json=availablePeers,proto3" json:"available_peers,omitempty"`
	VersionCount   int32                  `protobuf:"varint,5,opt,name=version_count,json=versionCount,proto3" json:"version_count,omitempty"`
	SyncPercentage float32                `protobuf:"fixed32,6,opt,name=sync_percentage,json=syncPercentage,proto3" json:"sync_percentage,omitempty"`
	LastSyncTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfoResponse) Reset() {
	*x = FileInfoResponse{}
	mi := &file_api_proto_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResponse) ProtoMessage() {}

func (x *FileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResponse.ProtoReflect.Descriptor instead.
func (*FileInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileInfoResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileInfoResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FileInfoResponse) GetAvailablePeers() []string {
	if x != nil {
		return x.AvailablePeers
	}
	return nil
}

func (x *FileInfoResponse) GetVersionCount() int32 {
	if x != nil {
		return x.VersionCount
	}
	return 0
}

func (x *FileInfoResponse) GetSyncPercentage() float32 {
	if x != nil {
		return x.SyncPercentage
	}
	return 0
}

func (x *FileInfoResponse) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_api_proto_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileVersionsRequest) Reset() {
	*x = GetFileVersionsRequest{}
	mi := &file_api_proto_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileVersionsRequest) ProtoMessage() {}

func (x *GetFileVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetFileVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileVersionsRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type FileVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Versions      []*FileVersion         `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersionsResponse) Reset() {
	*x = FileVersionsResponse{}
	mi := &file_api_proto_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersionsResponse) ProtoMessage() {}

func (x *FileVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersionsResponse.ProtoReflect.Descriptor instead.
func (*FileVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{10}
}

func (x *FileVersionsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileVersionsResponse) GetVersions() []*FileVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type RestoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFileRequest) Reset() {
	*x = RestoreFileRequest{}
	mi := &file_api_proto_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFileRequest) ProtoMessage() {}

func (x *RestoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFileRequest.ProtoReflect.Descriptor instead.
func (*RestoreFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RestoreFileRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	File          *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_api_proto_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{12}
}

func (x *FileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

var File_api_proto_file_proto protoreflect.FileDescriptor

const file_api_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/file.proto\x12\n" +
	"aether.api\x1a\x16api/proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12#\n" +
	"\rrelative_path\x18\x03 \x01(\tR\frelativePath\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x1f\n" +
	"\vglobal_hash\x18\x06 \x01(\tR\n" +
	"globalHash\x12\x1f\n" +
	"\vchunk_count\x18\a \x01(\x05R\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\x12/\n" +
	"\x13device_availability\x18\x05 \x03(\tR\x12deviceAvailability\"\xb3\x02\n" +
	"\vFileVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\rversionNumber\x12\x1f\n" +
	"\vbackup_path\x18\x04 \x01(\tR\n" +
	"backupPath\x12#\n" +
	"\roriginal_path\x18\x05 \x01(\tR\foriginalPath\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\a \x01(\tR\x04hash\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x12created_by_peer_id\x18\t \x01(\tR\x0fcreatedByPeerId\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.aether.api.PaginationRequestR\n" +
	"pagination\"{\n" +
	"\x11ListFilesResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.aether.api.FileR\x05files\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.aether.api.PaginationResponseR\n" +
	"pagination\"-\n" +
	"\x12GetFileInfoRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xc8\x02\n" +
	"\x10FileInfoResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x12$\n" +
	"\x04file\x18\x02 \x01(\v2\x10.aether.api.FileR\x04file\x12)\n" +
	"\x06chunks\x18\x03 \x03(\v2\x11.aether.api.ChunkR\x06chunks\x12'\n" +
	"\x0favailable_peers\x18\x04 \x03(\tR\x0eavailablePeers\x12#\n" +
	"\rversion_count\x18\x05 \x01(\x05R\fversionCount\x12'\n" +
	"\x0fsync_percentage\x18\x06 \x01(\x02R\x0esyncPercentage\x12@\n" +
	"\x0elast_sync_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"1\n" +
	"\x16GetFileVersionsRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"w\n" +
	"\x14FileVersionsResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x123\n" +
	"\bversions\x18\x02 \x03(\v2\x17.aether.api.FileVersionR\bversions\"L\n" +
	"\x12RestoreFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"`\n" +
	"\fFileResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x12$\n" +
	"\x04file\x18\x02 \x01(\v2\x10.aether.api.FileR\x04file2\xc2\x03\n" +
	"\vFileService\x12?\n" +
	"\aGetFile\x12\x1a.aether.api.GetFileRequest\x1a\x18.aether.api.FileResponse\x12H\n" +
	"\tListFiles\x12\x1c.aether.api.ListFilesRequest\x1a\x1d.aether.api.ListFilesResponse\x12K\n" +
	"\vGetFileInfo\x12\x1e.aether.api.GetFileInfoRequest\x1a\x1c.aether.api.FileInfoResponse\x12?\n" +
	"\n" +
	"DeleteFile\x12\x1d.aether.api.DeleteFileRequest\x1a\x12.aether.api.Status\x12W\n" +
	"\x0fGetFileVersions\x12\".aether.api.GetFileVersionsRequest\x1a .aether.api.FileVersionsResponse\x12A\n" +
	"\vRestoreFile\x12\x1e.aether.api.RestoreFileRequest\x1a\x12.aether.api.StatusB(Z&github.com/aether/sync/api/proto;protob\x06proto3"

var (
	file_api_proto_file_proto_rawDescOnce sync.Once
	file_api_proto_file_proto_rawDescData []byte
)

func file_api_proto_file_proto_rawDescGZIP() []byte {
	file_api_proto_file_proto_rawDescOnce.Do(func() {
		file_api_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_file_proto_rawDesc), len(file_api_proto_file_proto_rawDesc)))
	})
	return file_api_proto_file_proto_rawDescData
}

var file_api_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_file_proto_goTypes = []any{
	(*File)(nil),                   // 0: aether.api.File
	(*Chunk)(nil),                  // 1: aether.api.Chunk
	(*FileVersion)(nil),            // 2: aether.api.FileVersion
	(*GetFileRequest)(nil),         // 3: aether.api.GetFileRequest
	(*ListFilesRequest)(nil),       // 4: aether.api.ListFilesRequest
	(*ListFilesResponse)(nil),      // 5: aether.api.ListFilesResponse
	(*GetFileInfoRequest)(nil),     // 6: aether.api.GetFileInfoRequest
	(*FileInfoResponse)(nil),       // 7: aether.api.FileInfoResponse
	(*DeleteFileRequest)(nil),      // 8: aether.api.DeleteFileRequest
	(*GetFileVersionsRequest)(nil), // 9: aether.api.GetFileVersionsRequest
	(*FileVersionsResponse)(nil),   // 10: aether.api.FileVersionsResponse
	(*RestoreFileRequest)(nil),     // 11: aether.api.RestoreFileRequest
	(*FileResponse)(nil),           // 12: aether.api.FileResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*PaginationRequest)(nil),      // 14: aether.api.PaginationRequest
	(*PaginationResponse)(nil),     // 15: aether.api.PaginationResponse
	(*Status)(nil),                 // 16: aether.api.Status
}
var file_api_proto_file_proto_depIdxs = []int32{
	13, // 0: aether.api.File.mod_time:type_name -> google.protobuf.Timestamp
	13, // 1: aether.api.File.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: aether.api.File.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: aether.api.FileVersion.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: aether.api.ListFilesRequest.pagination:type_name -> aether.api.PaginationRequest
	0,  // 5: aether.api.ListFilesResponse.files:type_name -> aether.api.File
	15, // 6: aether.api.ListFilesResponse.pagination:type_name -> aether.api.PaginationResponse
	16, // 7: aether.api.FileInfoResponse.status:type_name -> aether.api.Status
	0,  // 8: aether.api.FileInfoResponse.file:type_name -> aether.api.File
	1,  // 9: aether.api.FileInfoResponse.chunks:type_name -> aether.api.Chunk
	13, // 10: aether.api.FileInfoResponse.last_sync_time:type_name -> google.protobuf.Timestamp
	16, // 11: aether.api.FileVersionsResponse.status:type_name -> aether.api.Status
	2,  // 12: aether.api.FileVersionsResponse.versions:type_name -> aether.api.FileVersion
	16, // 13: aether.api.FileResponse.status:type_name -> aether.api.Status
	0,  // 14: aether.api.FileResponse.file:type_name -> aether.api.File
	3,  // 15: aether.api.FileService.GetFile:input_type -> aether.api.GetFileRequest
	4,  // 16: aether.api.FileService.ListFiles:input_type -> aether.api.ListFilesRequest
	6,  // 17: aether.api.FileService.GetFileInfo:input_type -> aether.api.GetFileInfoRequest
	8,  // 18: aether.api.FileService.DeleteFile:input_type -> aether.api.DeleteFileRequest
	9,  // 19: aether.api.FileService.GetFileVersions:input_type -> aether.api.GetFileVersionsRequest
	11, // 20: aether.api.FileService.RestoreFile:input_type -> aether.api.RestoreFileRequest
	12, // 21: aether.api.FileService.GetFile:output_type -> aether.api.FileResponse
	5,  // 22: aether.api.FileService.ListFiles:output_type -> aether.api.ListFilesResponse
	7,  // 23: aether.api.FileService.GetFileInfo:output_type -> aether.api.FileInfoResponse
	16, // 24: aether.api.FileService.DeleteFile:output_type -> aether.api.Status
	10, // 25: aether.api.FileService.GetFileVersions:output_type -> aether.api.FileVersionsResponse
	16, // 26: aether.api.FileService.RestoreFile:output_type -> aether.api.Status
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_file_proto_init() }
func file_api_proto_file_proto_init() {
	if File_api_proto_file_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_file_proto_rawDesc), len(file_api_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_file_proto_goTypes,
		DependencyIndexes: file_api_proto_file_proto_depIdxs,
		MessageInfos:      file_api_proto_file_proto_msgTypes,
	}.Build()
	File_api_proto_file_proto = out.File
	file_api_proto_file_proto_goTypes = nil
	file_api_proto_file_proto_depIdxs = nil
}
