// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/folder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	SyncMode      SyncMode               `protobuf:"varint,3,opt,name=sync_mode,json=syncMode,proto3,enum=aether.api.SyncMode" json:"sync_mode,omitempty"`
	LastScanTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_scan_time,json=lastScanTime,proto3" json:"last_scan_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_api_proto_folder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{0}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *Folder) GetSyncMode() SyncMode {
	if x != nil {
		return x.SyncMode
	}
	return SyncMode_SYNC_MODE_UNSPECIFIED
}

func (x *Folder) GetLastScanTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScanTime
	}
	return nil
}

func (x *Folder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Folder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Folder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	SyncMode      SyncMode               `protobuf:"varint,2,opt,name=sync_mode,json=syncMode,proto3,enum=aether.api.SyncMode" json:"sync_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFolderRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *CreateFolderRequest) GetSyncMode() SyncMode {
	if x != nil {
		return x.SyncMode
	}
	return SyncMode_SYNC_MODE_UNSPECIFIED
}

type GetFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolderRequest) Reset() {
	*x = GetFolderRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderRequest) ProtoMessage() {}

func (x *GetFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderRequest.ProtoReflect.Descriptor instead.
func (*GetFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{2}
}

func (x *GetFolderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{3}
}

func (x *ListFoldersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListFoldersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_api_proto_folder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{4}
}

func (x *ListFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *ListFoldersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	SyncMode      SyncMode               `protobuf:"varint,3,opt,name=sync_mode,json=syncMode,proto3,enum=aether.api.SyncMode" json:"sync_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFolderRequest) Reset() {
	*x = UpdateFolderRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFolderRequest) ProtoMessage() {}

func (x *UpdateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFolderRequest.ProtoReflect.Descriptor instead.
func (*UpdateFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFolderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFolderRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UpdateFolderRequest) GetSyncMode() SyncMode {
	if x != nil {
		return x.SyncMode
	}
	return SyncMode_SYNC_MODE_UNSPECIFIED
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFolderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToggleFolderActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFolderActiveRequest) Reset() {
	*x = ToggleFolderActiveRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFolderActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFolderActiveRequest) ProtoMessage() {}

func (x *ToggleFolderActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFolderActiveRequest.ProtoReflect.Descriptor instead.
func (*ToggleFolderActiveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{7}
}

func (x *ToggleFolderActiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleFolderActiveRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type FolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Folder        *Folder                `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderResponse) Reset() {
	*x = FolderResponse{}
	mi := &file_api_proto_folder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderResponse) ProtoMessage() {}

func (x *FolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderResponse.ProtoReflect.Descriptor instead.
func (*FolderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{8}
}

func (x *FolderResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type ScanFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanFolderRequest) Reset() {
	*x = ScanFolderRequest{}
	mi := &file_api_proto_folder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFolderRequest) ProtoMessage() {}

func (x *ScanFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFolderRequest.ProtoReflect.Descriptor instead.
func (*ScanFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{9}
}

func (x *ScanFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type ScanFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FilesFound    int32                  `protobuf:"varint,2,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesSaved    int32                  `protobuf:"varint,3,opt,name=files_saved,json=filesSaved,proto3" json:"files_saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanFolderResponse) Reset() {
	*x = ScanFolderResponse{}
	mi := &file_api_proto_folder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFolderResponse) ProtoMessage() {}

func (x *ScanFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_folder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFolderResponse.ProtoReflect.Descriptor instead.
func (*ScanFolderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_folder_proto_rawDescGZIP(), []int{10}
}

func (x *ScanFolderResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ScanFolderResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanFolderResponse) GetFilesSaved() int32 {
	if x != nil {
		return x.FilesSaved
	}
	return 0
}

var File_api_proto_folder_proto protoreflect.FileDescriptor

const file_api_proto_folder_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/folder.proto\x12\n" +
	"aether.api\x1a\x16api/proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x121\n" +
	"\tsync_mode\x18\x03 \x01(\x0e2\x14.aether.api.SyncModeR\bsyncMode\x12@\n" +
	"\x0elast_scan_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastScanTime\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\x13CreateFolderRequest\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x121\n" +
	"\tsync_mode\x18\x02 \x01(\x0e2\x14.aether.api.SyncModeR\bsyncMode\"\"\n" +
	"\x10GetFolderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"t\n" +
	"\x12ListFoldersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.aether.api.PaginationRequestR\n" +
	"pagination\"\x83\x01\n" +
	"\x13ListFoldersResponse\x12,\n" +
	"\afolders\x18\x01 \x03(\v2\x12.aether.api.FolderR\afolders\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.aether.api.PaginationResponseR\n" +
	"pagination\"w\n" +
	"\x13UpdateFolderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x121\n" +
	"\tsync_mode\x18\x03 \x01(\x0e2\x14.aether.api.SyncModeR\bsyncMode\"%\n" +
	"\x13DeleteFolderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x19ToggleFolderActiveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"h\n" +
	"\x0eFolderResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x12*\n" +
	"\x06folder\x18\x02 \x01(\v2\x12.aether.api.FolderR\x06folder\"0\n" +
	"\x11ScanFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"\x82\x01\n" +
	"\x12ScanFolderResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x12\x1f\n" +
	"\vfiles_found\x18\x02 \x01(\x05R\n" +
	"filesFound\x12\x1f\n" +
	"\vfiles_saved\x18\x03 \x01(\x05R\n" +
	"filesSaved2\xab\x04\n" +
	"\rFolderService\x12K\n" +
	"\fCreateFolder\x12\x1f.aether.api.CreateFolderRequest\x1a\x1a.aether.api.FolderResponse\x12E\n" +
	"\tGetFolder\x12\x1c.aether.api.GetFolderRequest\x1a\x1a.aether.api.FolderResponse\x12N\n" +
	"\vListFolders\x12\x1e.aether.api.ListFoldersRequest\x1a\x1f.aether.api.ListFoldersResponse\x12K\n" +
	"\fUpdateFolder\x12\x1f.aether.api.UpdateFolderRequest\x1a\x1a.aether.api.FolderResponse\x12C\n" +
	"\fDeleteFolder\x12\x1f.aether.api.DeleteFolderRequest\x1a\x12.aether.api.Status\x12W\n" +
	"\x12ToggleFolderActive\x12%.aether.api.ToggleFolderActiveRequest\x1a\x1a.aether.api.FolderResponse\x12K\n" +
	"\n" +
	"ScanFolder\x12\x1d.aether.api.ScanFolderRequest\x1a\x1e.aether.api.ScanFolderResponseB(Z&github.com/aether/sync/api/proto;protob\x06proto3"

var (
	file_api_proto_folder_proto_rawDescOnce sync.Once
	file_api_proto_folder_proto_rawDescData []byte
)

func file_api_proto_folder_proto_rawDescGZIP() []byte {
	file_api_proto_folder_proto_rawDescOnce.Do(func() {
		file_api_proto_folder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_folder_proto_rawDesc), len(file_api_proto_folder_proto_rawDesc)))
	})
	return file_api_proto_folder_proto_rawDescData
}

var file_api_proto_folder_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_folder_proto_goTypes = []any{
	(*Folder)(nil),                    // 0: aether.api.Folder
	(*CreateFolderRequest)(nil),       // 1: aether.api.CreateFolderRequest
	(*GetFolderRequest)(nil),          // 2: aether.api.GetFolderRequest
	(*ListFoldersRequest)(nil),        // 3: aether.api.ListFoldersRequest
	(*ListFoldersResponse)(nil),       // 4: aether.api.ListFoldersResponse
	(*UpdateFolderRequest)(nil),       // 5: aether.api.UpdateFolderRequest
	(*DeleteFolderRequest)(nil),       // 6: aether.api.DeleteFolderRequest
	(*ToggleFolderActiveRequest)(nil), // 7: aether.api.ToggleFolderActiveRequest
	(*FolderResponse)(nil),            // 8: aether.api.FolderResponse
	(*ScanFolderRequest)(nil),         // 9: aether.api.ScanFolderRequest
	(*ScanFolderResponse)(nil),        // 10: aether.api.ScanFolderResponse
	(SyncMode)(0),                     // 11: aether.api.SyncMode
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*PaginationRequest)(nil),         // 13: aether.api.PaginationRequest
	(*PaginationResponse)(nil),        // 14: aether.api.PaginationResponse
	(*Status)(nil),                    // 15: aether.api.Status
}
var file_api_proto_folder_proto_depIdxs = []int32{
	11, // 0: aether.api.Folder.sync_mode:type_name -> aether.api.SyncMode
	12, // 1: aether.api.Folder.last_scan_time:type_name -> google.protobuf.Timestamp
	12, // 2: aether.api.Folder.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: aether.api.Folder.updated_at:type_name -> google.protobuf.Timestamp
	11, // 4: aether.api.CreateFolderRequest.sync_mode:type_name -> aether.api.SyncMode
	13, // 5: aether.api.ListFoldersRequest.pagination:type_name -> aether.api.PaginationRequest
	0,  // 6: aether.api.ListFoldersResponse.folders:type_name -> aether.api.Folder
	14, // 7: aether.api.ListFoldersResponse.pagination:type_name -> aether.api.PaginationResponse
	11, // 8: aether.api.UpdateFolderRequest.sync_mode:type_name -> aether.api.SyncMode
	15, // 9: aether.api.FolderResponse.status:type_name -> aether.api.Status
	0,  // 10: aether.api.FolderResponse.folder:type_name -> aether.api.Folder
	15, // 11: aether.api.ScanFolderResponse.status:type_name -> aether.api.Status
	1,  // 12: aether.api.FolderService.CreateFolder:input_type -> aether.api.CreateFolderRequest
	2,  // 13: aether.api.FolderService.GetFolder:input_type -> aether.api.GetFolderRequest
	3,  // 14: aether.api.FolderService.ListFolders:input_type -> aether.api.ListFoldersRequest
	5,  // 15: aether.api.FolderService.UpdateFolder:input_type -> aether.api.UpdateFolderRequest
	6,  // 16: aether.api.FolderService.DeleteFolder:input_type -> aether.api.DeleteFolderRequest
	7,  // 17: aether.api.FolderService.ToggleFolderActive:input_type -> aether.api.ToggleFolderActiveRequest
	9,  // 18: aether.api.FolderService.ScanFolder:input_type -> aether.api.ScanFolderRequest
	8,  // 19: aether.api.FolderService.CreateFolder:output_type -> aether.api.FolderResponse
	8,  // 20: aether.api.FolderService.GetFolder:output_type -> aether.api.FolderResponse
	4,  // 21: aether.api.FolderService.ListFolders:output_type -> aether.api.ListFoldersResponse
	8,  // 22: aether.api.FolderService.UpdateFolder:output_type -> aether.api.FolderResponse
	15, // 23: aether.api.FolderService.DeleteFolder:output_type -> aether.api.Status
	8,  // 24: aether.api.FolderService.ToggleFolderActive:output_type -> aether.api.FolderResponse
	10, // 25: aether.api.FolderService.ScanFolder:output_type -> aether.api.ScanFolderResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_folder_proto_init() }
func file_api_proto_folder_proto_init() {
	if File_api_proto_folder_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_folder_proto_rawDesc), len(file_api_proto_folder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_folder_proto_goTypes,
		DependencyIndexes: file_api_proto_folder_proto_depIdxs,
		MessageInfos:      file_api_proto_folder_proto_msgTypes,
	}.Build()
	File_api_proto_folder_proto = out.File
	file_api_proto_folder_proto_goTypes = nil
	file_api_proto_folder_proto_depIdxs = nil
}
