// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncEvent_EventType int32

const (
	SyncEvent_EVENT_TYPE_UNSPECIFIED    SyncEvent_EventType = 0
	SyncEvent_EVENT_TYPE_FILE_ADDED     SyncEvent_EventType = 1
	SyncEvent_EVENT_TYPE_FILE_MODIFIED  SyncEvent_EventType = 2
	SyncEvent_EVENT_TYPE_FILE_DELETED   SyncEvent_EventType = 3
	SyncEvent_EVENT_TYPE_SYNC_STARTED   SyncEvent_EventType = 4
	SyncEvent_EVENT_TYPE_SYNC_COMPLETED SyncEvent_EventType = 5
	SyncEvent_EVENT_TYPE_SYNC_FAILED    SyncEvent_EventType = 6
)

// Enum value maps for SyncEvent_EventType.
var (
	SyncEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_FILE_ADDED",
		2: "EVENT_TYPE_FILE_MODIFIED",
		3: "EVENT_TYPE_FILE_DELETED",
		4: "EVENT_TYPE_SYNC_STARTED",
		5: "EVENT_TYPE_SYNC_COMPLETED",
		6: "EVENT_TYPE_SYNC_FAILED",
	}
	SyncEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_FILE_ADDED":     1,
		"EVENT_TYPE_FILE_MODIFIED":  2,
		"EVENT_TYPE_FILE_DELETED":   3,
		"EVENT_TYPE_SYNC_STARTED":   4,
		"EVENT_TYPE_SYNC_COMPLETED": 5,
		"EVENT_TYPE_SYNC_FAILED":    6,
	}
)

func (x SyncEvent_EventType) Enum() *SyncEvent_EventType {
	p := new(SyncEvent_EventType)
	*p = x
	return p
}

func (x SyncEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sync_proto_enumTypes[0].Descriptor()
}

func (SyncEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_proto_sync_proto_enumTypes[0]
}

func (x SyncEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncEvent_EventType.Descriptor instead.
func (SyncEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{9, 0}
}

type SyncFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TargetPeerIds []string               `protobuf:"bytes,2,rep,name=target_peer_ids,json=targetPeerIds,proto3" json:"target_peer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFileRequest) Reset() {
	*x = SyncFileRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFileRequest) ProtoMessage() {}

func (x *SyncFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFileRequest.ProtoReflect.Descriptor instead.
func (*SyncFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SyncFileRequest) GetTargetPeerIds() []string {
	if x != nil {
		return x.TargetPeerIds
	}
	return nil
}

type SyncFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      *SyncProgress          `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFileResponse) Reset() {
	*x = SyncFileResponse{}
	mi := &file_api_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFileResponse) ProtoMessage() {}

func (x *SyncFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFileResponse.ProtoReflect.Descriptor instead.
func (*SyncFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SyncFileResponse) GetProgress() *SyncProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetSyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetSyncStatusRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type SyncStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SyncStatus    *SyncStatus            `protobuf:"bytes,2,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusResponse) Reset() {
	*x = SyncStatusResponse{}
	mi := &file_api_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusResponse) ProtoMessage() {}

func (x *SyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SyncStatusResponse) GetSyncStatus() *SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return nil
}

type SyncStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FolderId         string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	TotalFiles       int32                  `protobuf:"varint,2,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	SyncedFiles      int32                  `protobuf:"varint,3,opt,name=synced_files,json=syncedFiles,proto3" json:"synced_files,omitempty"`
	PendingFiles     int32                  `protobuf:"varint,4,opt,name=pending_files,json=pendingFiles,proto3" json:"pending_files,omitempty"`
	TotalSize        int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	SyncedSize       int64                  `protobuf:"varint,6,opt,name=synced_size,json=syncedSize,proto3" json:"synced_size,omitempty"`
	LastSyncTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	IsSyncing        bool                   `protobuf:"varint,8,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	CurrentOperation string                 `protobuf:"bytes,9,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_api_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncStatus) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *SyncStatus) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *SyncStatus) GetSyncedFiles() int32 {
	if x != nil {
		return x.SyncedFiles
	}
	return 0
}

func (x *SyncStatus) GetPendingFiles() int32 {
	if x != nil {
		return x.PendingFiles
	}
	return 0
}

func (x *SyncStatus) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SyncStatus) GetSyncedSize() int64 {
	if x != nil {
		return x.SyncedSize
	}
	return 0
}

func (x *SyncStatus) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *SyncStatus) GetIsSyncing() bool {
	if x != nil {
		return x.IsSyncing
	}
	return false
}

func (x *SyncStatus) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

type SyncProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BytesTransferred int64                  `protobuf:"varint,1,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Percentage       float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	SpeedBps         int64                  `protobuf:"varint,4,opt,name=speed_bps,json=speedBps,proto3" json:"speed_bps,omitempty"`
	EtaSeconds       int64                  `protobuf:"varint,5,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncProgress) Reset() {
	*x = SyncProgress{}
	mi := &file_api_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProgress) ProtoMessage() {}

func (x *SyncProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProgress.ProtoReflect.Descriptor instead.
func (*SyncProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncProgress) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *SyncProgress) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SyncProgress) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *SyncProgress) GetSpeedBps() int64 {
	if x != nil {
		return x.SpeedBps
	}
	return 0
}

func (x *SyncProgress) GetEtaSeconds() int64 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

type PauseSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSyncRequest) Reset() {
	*x = PauseSyncRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSyncRequest) ProtoMessage() {}

func (x *PauseSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSyncRequest.ProtoReflect.Descriptor instead.
func (*PauseSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *PauseSyncRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type ResumeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSyncRequest) Reset() {
	*x = ResumeSyncRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSyncRequest) ProtoMessage() {}

func (x *ResumeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSyncRequest.ProtoReflect.Descriptor instead.
func (*ResumeSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeSyncRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type WatchSyncEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncEventsRequest) Reset() {
	*x = WatchSyncEventsRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncEventsRequest) ProtoMessage() {}

func (x *WatchSyncEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{8}
}

func (x *WatchSyncEventsRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type SyncEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     SyncEvent_EventType    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=aether.api.SyncEvent_EventType" json:"event_type,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_api_proto_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{9}
}

func (x *SyncEvent) GetEventType() SyncEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return SyncEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *SyncEvent) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SyncEvent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SyncEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SyncEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_sync_proto protoreflect.FileDescriptor

const file_api_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/sync.proto\x12\n" +
	"aether.api\x1a\x16api/proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x0fSyncFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12&\n" +
	"\x0ftarget_peer_ids\x18\x02 \x03(\tR\rtargetPeerIds\"t\n" +
	"\x10SyncFileResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x124\n" +
	"\bprogress\x18\x02 \x01(\v2\x18.aether.api.SyncProgressR\bprogress\"3\n" +
	"\x14GetSyncStatusRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"y\n" +
	"\x12SyncStatusResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.aether.api.StatusR\x06status\x127\n" +
	"\vsync_status\x18\x02 \x01(\v2\x16.aether.api.SyncStatusR\n" +
	"syncStatus\"\xe0\x02\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vtotal_files\x18\x02 \x01(\x05R\n" +
	"totalFiles\x12!\n" +
	"\fsynced_files\x18\x03 \x01(\x05R\vsyncedFiles\x12#\n" +
	"\rpending_files\x18\x04 \x01(\x05R\fpendingFiles\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vsynced_size\x18\x06 \x01(\x03R\n" +
	"syncedSize\x12@\n" +
	"\x0elast_sync_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12\x1d\n" +
	"\n" +
	"is_syncing\x18\b \x01(\bR\tisSyncing\x12+\n" +
	"\x11current_operation\x18\t \x01(\tR\x10currentOperation\"\xba\x01\n" +
	"\fSyncProgress\x12+\n" +
	"\x11bytes_transferred\x18\x01 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\x12\x1b\n" +
	"\tspeed_bps\x18\x04 \x01(\x03R\bspeedBps\x12\x1f\n" +
	"\veta_seconds\x18\x05 \x01(\x03R\n" +
	"etaSeconds\"/\n" +
	"\x10PauseSyncRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"0\n" +
	"\x11ResumeSyncRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"5\n" +
	"\x16WatchSyncEventsRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"\xad\x03\n" +
	"\tSyncEvent\x12>\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1f.aether.api.SyncEvent.EventTypeR\teventType\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xd5\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_FILE_ADDED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_FILE_MODIFIED\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_FILE_DELETED\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_SYNC_STARTED\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_SYNC_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16EVENT_TYPE_SYNC_FAILED\x10\x062\xf7\x02\n" +
	"\vSyncService\x12E\n" +
	"\bSyncFile\x12\x1b.aether.api.SyncFileRequest\x1a\x1c.aether.api.SyncFileResponse\x12Q\n" +
	"\rGetSyncStatus\x12 .aether.api.GetSyncStatusRequest\x1a\x1e.aether.api.SyncStatusResponse\x12=\n" +
	"\tPauseSync\x12\x1c.aether.api.PauseSyncRequest\x1a\x12.aether.api.Status\x12?\n" +
	"\n" +
	"ResumeSync\x12\x1d.aether.api.ResumeSyncRequest\x1a\x12.aether.api.Status\x12N\n" +
	"\x0fWatchSyncEvents\x12\".aether.api.WatchSyncEventsRequest\x1a\x15.aether.api.SyncEvent0\x01B(Z&github.com/aether/sync/api/proto;protob\x06proto3"

var (
	file_api_proto_sync_proto_rawDescOnce sync.Once
	file_api_proto_sync_proto_rawDescData []byte
)

func file_api_proto_sync_proto_rawDescGZIP() []byte {
	file_api_proto_sync_proto_rawDescOnce.Do(func() {
		file_api_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)))
	})
	return file_api_proto_sync_proto_rawDescData
}

var file_api_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_sync_proto_goTypes = []any{
	(SyncEvent_EventType)(0),       // 0: aether.api.SyncEvent.EventType
	(*SyncFileRequest)(nil),        // 1: aether.api.SyncFileRequest
	(*SyncFileResponse)(nil),       // 2: aether.api.SyncFileResponse
	(*GetSyncStatusRequest)(nil),   // 3: aether.api.GetSyncStatusRequest
	(*SyncStatusResponse)(nil),     // 4: aether.api.SyncStatusResponse
	(*SyncStatus)(nil),             // 5: aether.api.SyncStatus
	(*SyncProgress)(nil),           // 6: aether.api.SyncProgress
	(*PauseSyncRequest)(nil),       // 7: aether.api.PauseSyncRequest
	(*ResumeSyncRequest)(nil),      // 8: aether.api.ResumeSyncRequest
	(*WatchSyncEventsRequest)(nil), // 9: aether.api.WatchSyncEventsRequest
	(*SyncEvent)(nil),              // 10: aether.api.SyncEvent
	(*Status)(nil),                 // 11: aether.api.Status
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_api_proto_sync_proto_depIdxs = []int32{
	11, // 0: aether.api.SyncFileResponse.status:type_name -> aether.api.Status
	6,  // 1: aether.api.SyncFileResponse.progress:type_name -> aether.api.SyncProgress
	11, // 2: aether.api.SyncStatusResponse.status:type_name -> aether.api.Status
	5,  // 3: aether.api.SyncStatusResponse.sync_status:type_name -> aether.api.SyncStatus
	12, // 4: aether.api.SyncStatus.last_sync_time:type_name -> google.protobuf.Timestamp
	0,  // 5: aether.api.SyncEvent.event_type:type_name -> aether.api.SyncEvent.EventType
	12, // 6: aether.api.SyncEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 7: aether.api.SyncService.SyncFile:input_type -> aether.api.SyncFileRequest
	3,  // 8: aether.api.SyncService.GetSyncStatus:input_type -> aether.api.GetSyncStatusRequest
	7,  // 9: aether.api.SyncService.PauseSync:input_type -> aether.api.PauseSyncRequest
	8,  // 10: aether.api.SyncService.ResumeSync:input_type -> aether.api.ResumeSyncRequest
	9,  // 11: aether.api.SyncService.WatchSyncEvents:input_type -> aether.api.WatchSyncEventsRequest
	2,  // 12: aether.api.SyncService.SyncFile:output_type -> aether.api.SyncFileResponse
	4,  // 13: aether.api.SyncService.GetSyncStatus:output_type -> aether.api.SyncStatusResponse
	11, // 14: aether.api.SyncService.PauseSync:output_type -> aether.api.Status
	11, // 15: aether.api.SyncService.ResumeSync:output_type -> aether.api.Status
	10, // 16: aether.api.SyncService.WatchSyncEvents:output_type -> aether.api.SyncEvent
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_sync_proto_init() }
func file_api_proto_sync_proto_init() {
	if File_api_proto_sync_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sync_proto_goTypes,
		DependencyIndexes: file_api_proto_sync_proto_depIdxs,
		EnumInfos:         file_api_proto_sync_proto_enumTypes,
		MessageInfos:      file_api_proto_sync_proto_msgTypes,
	}.Build()
	File_api_proto_sync_proto = out.File
	file_api_proto_sync_proto_goTypes = nil
	file_api_proto_sync_proto_depIdxs = nil
}
